import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Styles from '@/styles/buscapokemon.module.css'
import Header from '@/components/header'
import React, { useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

export async function puxaPokemon(pokemon) {
  var resp = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemon}`)
  var resp2 = await resp.json()
  return resp2
}
export default function Home() {
  const searchParams = useSearchParams();
  const pokemon = searchParams.get('pokemon')
  const [pokeDados, setpokeDados] = useState(null)
  const [carregar, setCarregar] = useState(true)
  useEffect(() => {
    if (pokemon !== null) {
      puxaPokemon(pokemon).then((e) => { setpokeDados(e) })

      setTimeout(() => {
        setCarregar(false)
        console.log(pokeDados);
      }, 500);
    }
  }, pokemon)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <form className={Styles.form} action='/buscapokemon' method='GET'>
        <input type="text" name='pokemon' placeholder='Digite o Nome do Pokemon...'/>
        <input type="submit" value="Pesquisar..." />
      </form>
      {
        pokemon !== null && pokeDados !== null ? !carregar ?
          <div className={Styles.pokedex}>
            <label className={Styles.nome}>{pokeDados?.name}</label>
            <img className={Styles.sprite} src={pokeDados?.sprites?.versions['generation-v']['black-white']?.animated?.front_default} />
            <div className={Styles.tipos}>
              {pokeDados?.types?.map((e, index) => { return <label className={Styles.tipo} key={index}>{e?.type?.name}</label> })}
            </div>
            <label className={Styles.indice}>{pokeDados?.game_indices[0]?.game_index}</label>
          </div>
          :
          <label> Carregando...</label>
          :
          <></>
      }
    </>
  )
}