import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Styles from '@/styles/crianome.module.css'
import Header from '@/components/header'
import React, { useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export async function criaNome(){
var resp= await fetch(`https://randomuser.me/api/`)
var resp2= await resp.json()
return resp2
}
export default function Home() {
  const [nome, setNome] = useState({})
  const [carregar, setCarregar] = useState(true)
  useEffect(() => {
   
      criaNome().then((e) => { setNome(e) })

      setTimeout(() => {
        setCarregar(false)
        console.log(nome);
      }, 500);

  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <form className={Styles.form} action='/crianome' method='GET'>
         <input type="submit" value="Clique aqui para gerar um nome para seu pokemon!" />
      </form>
      {
        !carregar && nome?.results[0]?.name?.first !== null?
        <div className={Styles.nome}>
          <label>
            {
             nome?.results[0]?.name?.first
            }
          </label>
        </div>
        :
        <label>Carregando...</label>
      }
    </>
  )
}